### ISSUE TITLE
Add specific multipliers for different dangers

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/RAMP-UA#70]
Thought I'd try creating an issue rather than emailing. @nnelissen & @Sparrow0hawk I've included you mostly for info.

@spoonerf & @jabrams23 I've added hazards multipliers that people give to the shops etc. once they have the disease, and also included a risk multiplier (we could have more of these in the future to model the impacts of some people being more likely to contract the disease than others).

In the `default.yml` file there is now:

```
microsim_calibration:
  # These multiply the amount of hazard that individuals pass on to shops etc:
  hazard_multiplier_presymptomatic: 1.0
  hazard_multiplier_asymptomatic: 1.0
  hazard_multiplier_symptomatic: 1.0
  # This multiplies the risk received as individuals visit shops etc.
  risk_multiplier: 1.0
```

The changes are on my branch (`dev_NM`): https://github.com/Urban-Analytics/RAMP-UA/commit/f967e1cbe82383d39777cb41822c64f49611e0f0

I've checked that the parameters get read in properly, which is fine, but I haven't been able to test it though because I am getting a problem with the libraries; see https://github.com/Urban-Analytics/RAMP-UA/issues/69 

If these multipliers aren't urgent then I can sort them out when I get back from holiday in 10 days. But if you want them sooner could you try running my branch to see if they work? Let me know if they don't and I can probably have a look at it while I'm off.
